version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - dist-server/**/*
    - public/**/*
    - node_modules/**/*
    - package.json
    - Procfile

