version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Starting pre-build phase
  build:
    commands:
      - echo Building the project
      - npm run build  # or npm run transpile if using babel
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - dist-server/**/*  # Include all built files in dist-server
